name: "Generate Graph"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install graphviz 
        run: sudo apt-get update && sudo apt-get install -y graphviz curl

      - name: Get linfo
        run: >
          curl https://github.com/netkit-jh/netkit-jh-build/releases/download/2.0.0/netkit-core-2.0.0.tar.bz2 -o netkit-core.tar.bz2
          sudo tar -xf netkit-core.tar.bz2 -C /opt/
	  


      - name: Generate graph
        run: env NETKIT_HOME=/opt/netkit-jh bash /opt/netkit-jh/bin/linfo --map=graph.png

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Graph"
          files: |
            graph.png
